config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

  get '/', to: 'home#index'

  devise_for :users
  resources :receipts do
    resources :comments
  end
  resources :my_receipts
  resources :home, only: [:index]
  resources :articles
  resources :categories
  resources :receipt_categories

  namespace :admin do
    resources :users, only: [:index, :update] do
      member do
        post :ban
        post :unban
      end
    end
    resources :users, only: [:index]
    resources :articles
    resources :categories
    resources :receipts
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get '/', to: 'home#index'
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}/receipts")

end

app/models/article.rb
class Article < ActiveRecord::Base
  before_save :set_articles_publishing_time

  validates :title, :description, presence: true

  scope :published, -> { where(published: true) }

  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/articles/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/articles/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  self.per_page = 5

  # pievieno publicēšanas laiku
  def set_articles_publishing_time
    self.published_at = self.published? ? Time.now : nil
  end
end

# == Schema Information
#
# Table name: articles
#
#  id                 :integer          not null, primary key
#  title              :string
#  description        :text
#  published          :boolean          default(FALSE)
#  published_at       :datetime
#  created_at         :datetime
#  updated_at         :datetime
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  before_action :set_article, only: [:edit, :update, :destroy]

  # GET admin/articles
  def index
    @articles = ::Article.page(params[:page]).order(published_at: :desc)
  end

  # GET admin/articles/new
  def new
    @article = ::Article.new
  end

  # GET admin/articles/edit
  def edit
  end

  # POST admin/articles
  def create
    @article = ::Article.new(article_params)

    if @article.save
      redirect_to admin_articles_path, notice: t('.notice')
    else
      render action: :new
    end
  end

  # PATCH/PUT admin/articles/1
  def update
    if @article.update(article_params)
      redirect_to admin_articles_path, notice: t('.notice')
    else
      render action: :edit
    end
  end

  # DELETE admin/articles/1
  def destroy
    @article.destroy
    redirect_to admin_articles_path, notice: t('.notice')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = ::Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(
        :title, :description, :published, :published_at, :photo
      )
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout "home"
  #   GET articles
  def index
    @articles = Article.where(published: true).page(params[:page]).order(published_at: :desc)
  end
end

app/views/admin/articles/_form.html.haml
= simple_form_for @article, url: url, html: { class: "input-form" } do |f|
  - if @article.errors.any?
    .error_explanation
      %h2= pluralize(@article.errors.count, t('error'))

      %ul
      - @article.errors.full_messages.each do |message|
        %li= message

  .form-group
    = f.input :title
    = f.input :description
    = f.file_field :photo
    = f.input :published, as: :boolean

  .form-actions
    = f.submit t('save'), class: "btn btn-default"
    = link_to t('back'), admin_articles_path, class: "btn btn-default"

app/views/admin/articles/edit.html.haml
.white-font.input
  %h2.middle= t('.edit_article')

  = render 'form', url: admin_article_path

app/views/admin/articles/index.html.haml
.white-font
  .list-header
    .top-options
      %h2= t('.list_of_articles')
      = link_to t('.add_article'), new_admin_article_path, class: "btn btn-default"

  / Visu ziņu attēlošana ar to iespējām
  %table.full-list
    %tr
      %th= t('.picture')
      %th= t('.title')
      %th= t('.published')
      %th= t('.publication_date')
      %th
      %th
    - @articles.each do |article|
      %tr
        %td= image_tag article.photo.url(:small)
        %td= article.title
        %td= boolean_value(article.published)
        %td= article.published_at
        %td= link_to t('edit'), edit_admin_article_path(article), class: "btn btn-info"
        %td= link_to t('destroy'), admin_article_path(article), method: :delete, class: "btn btn-danger" ,data: { confirm: t('are_you_sure') }

  .box
    = will_paginate @articles, renderer: BootstrapPagination::Rails

app/views/admin/articles/new.html.haml
.white-font.input
  %h2.middle= t('.new_article')

  = render 'form', url: admin_articles_path

app/views/admin/articles/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path