config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

  get '/', to: 'home#index'

  devise_for :users
  resources :receipts do
    resources :comments
  end
  resources :my_receipts
  resources :home, only: [:index]
  resources :articles
  resources :categories
  resources :receipt_categories

  namespace :admin do
    resources :users, only: [:index, :update] do
      member do
        post :ban
        post :unban
      end
    end
    resources :users, only: [:index]
    resources :articles
    resources :categories
    resources :receipts
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get '/', to: 'home#index'
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}/receipts")

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :receipt_categories
  has_many :categories, through: :receipt_categories

  before_save :receipt_published_at

  validates :description, presence: true
  validates :title, presence: true, uniqueness: true

  # Uzstāda recepšu skaitu vienā lapā
  self.per_page = 5

  # receptei pievieno bildi ar uzstādījumiem
  has_attached_file :photo, :styles => { :small => "150x150>", :medium => "300x300>" },
                    :url  => "/assets/receipts/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/receipts/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  # Uzstāda, ka recepte būs vērtējama ar dimensiju - vote
  ratyrate_rateable "vote"

  # Recepšu meklēšana visās publicētajās
  def self.search(query)
    where("title ilike ?", "%#{query}%")
  end

  scope :published, -> { where(published: true) }

  # pievieno receptes publicēšanas laiku
  def receipt_published_at
    self.published_at = self.published? ? Time.now : nil
  end
end

# == Schema Information
#
# Table name: receipts
#
#  id                 :integer          not null, primary key
#  user_id            :integer
#  title              :string
#  components         :text
#  description        :text
#  published          :boolean          default(FALSE)
#  published_at       :datetime
#  created_at         :datetime
#  updated_at         :datetime
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#

app/controllers/admin/receipts_controller.rb
class Admin::ReceiptsController < Admin::AdminController
  before_action :set_receipt, only: [:destroy]

  # DELETE /receipts/1
  def destroy
    @receipt.destroy
      redirect_to receipts_path, notice: t('.notice')
  end

  private

    def set_receipt
      @receipt = Receipt.find(params[:id])
    end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]
  layout "home"

  # GET /receipts
  # Redzamas visas kategorijas, publicētās receptes, sakārtotas pēc izveidošanas
  # datuma. Recepšu meklēsana
  def index
    @categories = Category.all
    if params[:search]
      @receipts = Receipt.where(published: true).search(params[:search]).page(params[:page]).order("created_at DESC")
    else
      @receipts = Receipt.where(published: true).page(params[:page]).order("created_at DESC")
    end
  end

  # GET /receipts/1
  # Redz receptes detaļas un tai pievienotos komentārus
  def show
    @comments = @receipt.comments.page(params[:page])
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # Jaunas receptes izveide.
  def create
    @receipt = Receipt.create(receipt_params.merge(user_id: current_user.id))
      if @receipt.save
        redirect_to my_receipts_path, notice: t('.notice')
      else
        render action: :new
      end
  end

  # PATCH/PUT /receipts/1
  # Receptes labošana
  def update
    @receipt = Receipt.find(params[:id])
    if @receipt.update(receipt_params)
      redirect_to my_receipts_path, notice: t('.notice')
    else
       render action: :edit
    end
  end

  # DELETE /receipts/1
  # Receptes dzēšana
  def destroy
    @receipt.destroy
      redirect_to my_receipts_path, notice: t('.notice')
  end

  private
    # Uzstāda recepti
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Receptes parametri
    def receipt_params
      params.require(:receipt).permit(
        :title, :description, :user_id, :photo, :components,
        :published, :published_at, :category_ids => [],
      )
    end
end

app/views/receipts/_form.html.haml
= simple_form_for @receipt, html: { class: "input-form" } do |f|
  - if @receipt.errors.any?
    .error_explanation
      %h2= pluralize(@receipt.errors.count, t('error'))

      %ul
      - @receipt.errors.full_messages.each do |message|
        %li= message

  .form-group
    = f.input :title
    = f.input :components
    = f.input :description
    = f.file_field :photo
    = f.input :published, as: :boolean

  / Receptei var pievienot kategoriju
  .form-group
    = f.label :category_id
    = f.collection_check_boxes :category_ids, Category.all, :id, :name

  .form-actions
    = f.submit t('save'), class: "btn btn-default"
    = link_to t('back'), my_receipts_path, class: "btn btn-default"

app/views/receipts/edit.html.haml
.white-font.input
  %h2.middle= t('.edit_receipt')

  = render 'form'

app/views/receipts/index.html.haml
.side
  %h3= t('.categories')
  - @categories.each do |category|
    %p= link_to category.name, category_path(category)

.main
  .white-font
    .main-top
      %h2= t('.main_title')
      / Recepšu meklēšana pēc nosaukuma
      = form_tag receipts_path, method: "get", class: "navbar-form", id: "search-form"   do
        .input-append
          = text_field_tag :search, params[:search], class: "span2", placeholder: t('.search')
          = submit_tag t('search'), name: nil, class: "btn btn-default btn-sm"

    - if @receipts.any?
      /Attēlots saraksts ar visām publicētajām receptēm
      %table.full-list
        - @receipts.each do |receipt|
          %tr
            %td
              %p= receipt.title
              %p= link_to (image_tag receipt.photo.url(:small)), receipt_path(receipt)
            %td= rating_for receipt, "vote", enable_half: true
            - if signed_in?
              - if current_user.is_admin
                %td= link_to t('destroy'), admin_receipt_path(receipt), method: :delete, class: "btn btn-danger", data: { confirm: "#{t('are_you_sure')}" }

      .box
        = will_paginate @receipts, renderer: BootstrapPagination::Rails

    - else
      .white-font.receipt-listing
        %h3.empty-message= t('.no_receipts')

app/views/receipts/new.html.haml
.white-font.input
  %h2.middle= t('.new_receipt')

  = render 'form'

app/views/receipts/show.html.haml
.white-font.input
  / Receptes nosaukums un tās vērtējums
  %h2.middle
    = @receipt.title
    = rating_for @receipt, "vote", enable_half: true

  / Receptes autors
  %h4.author
    = "#{t('.author')}: #{@receipt.user.username}"

  / Receptes bilde un tās sastāvdaļas
  %table.show-item
    %tr
      %td
        = image_tag @receipt.photo.url(:medium)
      %td
        .receipt-show
          %h4= t('.components')
          %p= @receipt.components

  / Receptes apraksts
  .receipt-show
    %h4= t('.description')
    %p= @receipt.description

    / Visi receptei pievienotie komentāri
    .comment-list
      %h4= "#{t('.comments')} #{@receipt.comments.count}"
      / Visi iesūtītie komentāri par recepti
      %table.show-comments
        - @comments.each do |comment|
          %tr
            %td= comment.user.username
            %td= comment.message
            - if user_signed_in?
              - if current_user.is_admin?
                %td= link_to t('destroy'), receipt_comment_path(@receipt, comment), method: :delete, class: "btn btn-danger", data: { confirm: "#{t('are_you_sure')}" }

        .box.comments
          = will_paginate @comments, renderer: BootstrapPagination::Rails

    / Ja lietotājs ir pieslēdzies, tad tas var izveidot komentāru
    - if user_signed_in?
      / Reģistrēts lietotājs var sniegt komentārus par recepti
      = simple_form_for ([@receipt, @receipt.comments.build]), html: { class: "comment-form" } do |f|
        .form-group
          = f.input :message
        .actions
          = f.submit t('submit'), class: "btn btn-default"