config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

  get '/', to: 'home#index'

  devise_for :users
  resources :receipts do
    resources :comments
  end
  resources :my_receipts
  resources :home, only: [:index]
  resources :articles
  resources :categories
  resources :receipt_categories

  namespace :admin do
    resources :users, only: [:index, :update] do
      member do
        post :ban
        post :unban
      end
    end
    resources :users, only: [:index]
    resources :articles
    resources :categories
    resources :receipts
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get '/', to: 'home#index'
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}/receipts")

end

app/controllers/my_receipts_controller.rb
class MyReceiptsController < ApplicationController
  layout "home"
  # GET /my_receipts
# Lietotājam redzamas viņa pievienotās receptes
  def index
    if current_user.present?
      @my_receipts = Receipt.where(user_id: current_user.id).page(params[:page]).order("created_at DESC")
    end
  end

  # GET /receipts/1
  def show
    @my_receipt = Receipt.find(params[:id])
  end
end

app/views/my_receipts/index.html.haml
.white-font
  - if user_signed_in?
    .my-receipts
      .top-options
        %h2= t('.main_title')
        = link_to t('.add_receipt'), new_receipt_path, class: "btn btn-default"
      - if @my_receipts.any?

        / Attēlots lietotāja izveidoto recepšu saraksts
        %table.element-list
          - @my_receipts.each do |receipt|
            %tr
              %td= link_to (image_tag receipt.photo.url(:small)), receipt_path(receipt)
              %td= receipt.title
              %td= rating_for receipt, "vote", enable_half: true
              %td= link_to t('edit'), edit_receipt_path(receipt), class: "btn btn-info"
              %td= link_to t('destroy'), receipt_path(receipt), method: :delete, class: "btn btn-danger", data: { confirm: "#{t('are_you_sure')}" }
      - else
        %h3.empty-message= t('.no_receipts')

    .box
      = will_paginate @my_receipts, renderer: BootstrapPagination::Rails

  - else
    .row
      %h2.main= "You must log in"