config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

  get '/', to: 'home#index'

  devise_for :users
  resources :receipts do
    resources :comments
  end
  resources :my_receipts
  resources :home, only: [:index]
  resources :articles
  resources :categories
  resources :receipt_categories

  namespace :admin do
    resources :users, only: [:index, :update] do
      member do
        post :ban
        post :unban
      end
    end
    resources :users, only: [:index]
    resources :articles
    resources :categories
    resources :receipts
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get '/', to: 'home#index'
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}/receipts")

end

app/views/layouts/application.html.haml
%html
  %head
    %title= [@page_title, 'Receptes'].compact.join(' - ')
    %meta{ content: @page_description, name: 'description' }
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
    = javascript_include_tag "application"
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
  %body{ id: "#{controller_name}_#{action_name}".dasherize }
    = yield

app/views/layouts/home.html.haml
%html
  %head
    %title Receptes
    %meta{ content: @page_description, name: 'description' }
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
    = javascript_include_tag "application"
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  %body{ id: "#{controller_name}_#{action_name}".dasherize }
    .wrapper
      #top-logo
      .header
        %a.navbar-brand{ href: "/home" } ReceptesLV
        %ul.nav.navbar-nav
          %li= link_to t('.home'), home_index_path
          %li= link_to t('.articles'), articles_path
          %li= link_to t('.receipts'), receipts_path
          - if user_signed_in?
            %li= link_to t('.my_receipts'), my_receipts_path
            - if current_user.is_admin?
              %li.dropdown
                %a.dropdown-toggle{ role: "button", data: { toggle: "dropdown" }, "aria-expanded" => false }
                  #{t('.admin_menu')}
                  %span.caret
                %ul.dropdown-menu{ role: "menu" }
                  %li= link_to t('.article_edditing'), admin_articles_path
                  %li= link_to t('.users'), admin_users_path
                  %li= link_to t('.categories'), admin_categories_path
          %li.dropdown
            %a.dropdown-toggle{ role: "button", data: { toggle: "dropdown" }, "aria-expanded" => false }
              #{t('.language')}
              %span.caret
            %ul.dropdown-menu.language-selection{ role: "menu" }
              %li= link_to "LV", locale: "lv"
              %li= link_to "EN", locale: "en"
        %ul.nav.navbar-nav.pull-right
          - if user_signed_in?
            %li= link_to current_user.username, edit_user_registration_path
            %li= link_to t('exit'), destroy_user_session_path, method: :delete
          - else
            %li= link_to t('register'), new_user_registration_path
            %li= link_to t('signin'), new_user_session_path

      .content
        .col-md-12.nopadding
          - if notice
            .alert.alert-success= notice
          - if alert
            .alert.alert-danger= alert

        = yield